### ISSUE TITLE
RFC: duplicate global theme settings to individual theme

### ISSUE THREAD

**Issue by DeeTigIT** [quelea-projection/Quelea#5] opened 2018-06-03 19:22 UTC
Intro:
We use a limited number of global themes for our ceremonies.  They have the same (translation) font settings, but have a different image background. During the ceremony, we switch to the required global theme prior to the next song that needs it. So far, we don't use the individual theme functionality. Currently, an individual theme for a song/timer/bible requires the use of the global 'Default theme'.

Request:
A selection button on the individual theme window of song/bible/timer, that allows the selection of a global theme. After selecting the global theme, the global theme settings are then copied/duplicated to the individual theme of the schedule item. And can further be adjusted on item level, if required, for example with a different background or text positioning. In this way one could quickly equip all the schedule items (song/bible/timer) with individual theme settings, and adjust only the exceptions on a item level.

Quelea manual, 2.1.2. Set an individual theme:
One thing to notice here is that the individual theme will override the default theme, but any other global theme (added by you or there by default) will override the individual settings you have made. (This is being discussed at the moment and will probably be an optional feature in the future.)

**Comment by berry120** [comment] 2018-06-04 07:29
Great points here - I've created issue #6 to hold theme discussions (as I think this needs wider input generally) and think I've covered everything you've mentioned in my points there - if not then feel free to add anything on that issue thread.

**Comment by berry120** [comment] 2018-06-04 07:29
Duplicate of #6

**Closed by berry120** 2018-06-04 07:29 UTC
