### ISSUE TITLE
Edit/change color or font of a line on one song slide

### ISSUE THREAD

**Issue by justine04661** [quelea-projection/Quelea#276] opened 2020-09-13 10:25 UTC
![quelea](https://user-images.githubusercontent.com/71211220/93015687-d6eafc80-f5ed-11ea-829e-f6dec235aab4.png)

Good day! May I ask if current Quelea can change the color or font of a line on one song slide. I just want to change the color of one line since continuous text with same color is not pleasing to the eye. Attached is a picture of my querie. Thank you!

**Comment by HeyITGuyFixIt** [comment] 2020-09-26 22:54
#29 talks about this issue. But there was last activity 2 years ago. Would be good to continue conversation about it again.

**Comment by berry120** [comment] 2020-12-18 00:00
We'll handle this as a duplicate of #29, as we wouldn't just do colour support - if we did this, we'd enable more extensive formatting support too. Afraid no work has been done on this as of yet though.

**Closed by berry120** 2020-12-18 00:00 UTC
