### ISSUE TITLE
Images in saved schedules replaced by images from Images library

### ISSUE THREAD

**Issue by joncojonathan** [quelea-projection/Quelea#359] opened 2021-05-16 12:02 UTC
When images are present in a saved schedule, and the schedule is reopened, the images get replaced with an image of the same name from the image library at `C:\Users\<username>\.quelea\img`.  Image groups are not affected by this bug.

**Steps to reproduce**
* Add an image called `Slide1.png` to the image library (it should then be found at `C:\Users\<username>\.quelea\img\Slide1.png`)
* Create a new schedule
* Insert a different image, also called `Slide1.png`, to the schedule
* Save your schedule
* Close Quelea
* Open your saved schedule (either by double clicking or opening via `File > Open`)
* Note the wrong image is shown in the preview and also in live view

The image does not need to be the first item in the schedule.  If multiple images are present in the schedule, they also get replaced where there is a name clash (unless they're in an image group).

**Reviewing the `.qsch` file**
Looking at `schedule.xml` (having extracted from the `.qsch` file) I can see the following XML in relation to images:
```
<fileimage>Slide1.png</fileimage>
<fileimage>Slide11.png</fileimage>
<fileimage>Slide12.png</fileimage>
```

In my test, files called `Slide1.png` and `Slide11.png` also existed in the image library.  These replaced the files of the same name in the schedule.

Inside the `resources` directory within the `.qsch` the _correct_ (desired) `Slide1.png` etc. is present.

**Conclusion**
When opening a saved schedule with images present, image files in the `resources` directory are ignored in favour of the local image gallery at `C:\Users\<username>\.quelea\img`.

**Observed in**
* Windows: 2020.0
* Windows: 2021.0 beta 1
* Linux: 2021.0 beta 1

**Comment by DeeTigIT** [comment] 2021-05-16 14:16
I'm not completely sure, but this could be related to #265 .

**Comment by joncojonathan** [comment] 2021-05-16 15:33
Yes, that looks very similar @DeeTigIT.  Seems the issue has been around for a while then.  I'm not familiar with that part of the code base but I might take a look see if I can work anything out.

**Comment by joncojonathan** [comment] 2021-05-16 15:40
I can confirm this problem exists in Linux also, having tested with 2021.0 beta 1.  Updated original description accordingly.  Installation was performed using snap (`sudo snap install --beta quelea`).

**Comment by berry120** [comment] 2021-08-15 20:46
@joncojonathan @DeeTigIT This issue should now be fixed - if one of you can confirm it's now as you expect, that'd be fantastic.

**Comment by DeeTigIT** [comment] 2021-08-17 20:01
I used the latest cross-platform CI, but the behaviour still appears to be present.

When I open the schedule "test - with embedded media (2).qsch" then in the "C:\Users\<account>\AppData\Local\Temp" the 2 media files are extracted:
- IMG_0319.JPG  this is the background image for the first (1st) schedule song
- SYOT3775.MP4  this is the background movie for the third (3rd) schedule song

The second (2nd) schedule song uses an image as song default.
The user option "Allow custom item themes to override global theme" is set.

Observations 1:
- background image for the first (1st) schedule song IS NOT SHOWN.
- second (2nd) schedule song uses image song default.
- background movie for the third (3rd) schedule song IS NOT SHOWN.

![S1-1](https://user-images.githubusercontent.com/39883796/129792051-034bd18c-eb54-4b85-90a4-e959b0cbdc14.JPG)

![S1-2](https://user-images.githubusercontent.com/39883796/129792069-aea30429-ba74-4955-8149-b89743b00cf7.JPG)

![S1-3](https://user-images.githubusercontent.com/39883796/129792081-5100c23a-7544-47fc-b699-c980d0662304.JPG)

As an experiment, I added:
- IMG_0319.JPG to the standard folder : c:\Users\<account>\.quelea\img\     (inital the JPG was absent in this folder)
- SYOT3775.MP4 to the standard folder : c:\Users\<account>\.quelea\vid\     (inital the MP4 was absent in this folder)
- re-opened the schedule "test - with embedded media (2).qsch" 

Observations 2:
- background image for the first (1st) schedule song IS SHOWN NOW.
- second (2nd) schedule song still uses image song default, as before.
- background movie for the third (3rd) schedule song IS SHOWN NOW.

![S2-1](https://user-images.githubusercontent.com/39883796/129792313-83068bfe-48c0-4650-b09a-9c600a9e0b0c.JPG)

![S2-2](https://user-images.githubusercontent.com/39883796/129792333-11ea6cc3-4fc9-44dd-8711-e78d2afbfd04.JPG)

![S2-3](https://user-images.githubusercontent.com/39883796/129792358-f852129d-a59f-493c-8702-8deeef6f1a5f.JPG)

**So it appears the code is still refering to the img en vid folders instead of the extaction folder "C:\Users\<account>\AppData\Local\Temp" containing the schedule background media ??**

[test - with embedded media (2).qsch.zip](https://github.com/quelea-projection/Quelea/files/7002716/test.-.with.embedded.media.2.qsch.zip)

**Comment by berry120** [comment] 2021-08-20 16:40
@DeeTigIT Ah, I believe @joncojonathan originally reported this to do with images (as in just image file behaviour) rather than to do with image / video background behaviour that's embedded in schedules, so that was all I fixed initially.

That being said, I think this behaviour definitely needs fixing too if feasible, so I've put in another fix - could you give that a try when you have time? Thanks!

**Comment by DeeTigIT** [comment] 2021-08-22 20:52
Did a test with the above schedule "test - with embedded media (2).qsch":

https://user-images.githubusercontent.com/39883796/130369554-2cee5880-6478-4c43-a01e-bd23ecf08fa9.mp4

- background image for the first (1st) schedule song IS SHOWN.
- second (2nd) schedule song still uses image song default, as before.
- background movie for the third (3rd) schedule song IS SHOWN.

Both background image and background movie were not present in img and vid folders.

**I did notice the following however. When this schedule is saved (or saved as) then the resources seem to disappear from the schedule. The resulting saved schedule doesn't contain the embedded resources anymore.** I recorded a video of this:

https://user-images.githubusercontent.com/39883796/130369718-7ce9d1f2-2a9f-4db1-8567-5b9a513eed6c.mp4

**Comment by berry120** [comment] 2021-08-24 20:20
@DeeTigIT Thanks for all this thorough testing, it's really helpful. Hopefully the bug with the resources disappearing after you saved should now be fixed.

Am I correct in thinking that the second behaviour is already as it should be (in that the second schedule song should use the image song default as it has been?)

**Comment by DeeTigIT** [comment] 2021-08-29 08:33
And I can confirm this: no more local refs in the schedule. 

Looking at the reproduction steps Jonathan described:

![S1](https://user-images.githubusercontent.com/39883796/131243699-199cb541-b610-4160-8ce5-ca90439bcc78.JPG)

I added 3 "Jonathan" images (Slide1.png, Slide2.png, Slide3.png) to the img folder.
And added 3 "other" images with equal names to the schedule: 1 individual image (Slide1.png) and an image groep (Slide1.png, Slide2.png, Slide3.png). The correct "other" images are shown upon projection in my test: they are stored in the resources folder within the schedule.

There is a point of attention. In the unlikely scenarion where **both** an img image and an "other" image **with the same name** are added to a schedule, then after re-openening the scheduling **the img is not shown** anymore but the "other" image in both cases.

**Comment by berry120** [comment] 2021-08-29 08:41
@DeeTigIT Thanks very much for that. In the interests of getting 2021.0 out the door and because this isn't a regression, I think the best thing to do is to migrate the bug you've noticed there to a new issue and work on it for 2022.0 instead (it requires me to have a careful think about how these image / video names are stored internally to prevent conflicts like this, so not a simple fix.) Hopefully the original issue and more should now be sorted, so I think that gives us a good enough basis to sign off 2021.0 with at least some noticeable improvement there.

Thanks again for all your testing!

**Closed by berry120** 2021-08-29 08:41 UTC
Labels: bug, accepted

**Comment by berry120** [comment] 2021-09-22 22:17
FYI: https://github.com/quelea-projection/Quelea/issues/378
