### ISSUE TITLE
SORT quelea.properties file upon Quelea exit

### ISSUE THREAD

**Issue by DeeTigIT** [quelea-projection/Quelea#279] opened 2020-09-21 04:06 UTC
Is it possible to sort the quelea.properties file when Quelea is ending? 
In that way the comparison of 2 properties files (current one, previous one) doesn't require a manual sorting anymore.
We use this comparison AFTER  the service to keep track of a property change DURING the service made by the Quelea operator.

**Comment by kavishdahekar** [comment] 2020-09-28 07:06
I'd like to contribute code for some of the issues.
But I'm not sure if there are any specific guidelines around `hacktoberfest` labelled issues or I can directly pick one and raise a PR?

**Comment by berry120** [comment] 2020-09-28 21:26
@kavishdahekar Any hacktoberfest related issue you're welcome to pick and raise a PR - so long as the contributing guide is followed then we should be good to accept those. For non hacktoberfest issues, probably best to comment on the issue to clarify what we think the fix should be (or just talk to us first in general.)

Also remember that PR's won't count towards Hacktoberfest until October 👍

**Comment by berry120** [comment] 2020-10-06 13:54
@kavishdahekar Do you want this to be assigned to you?

**Comment by kavishdahekar** [comment] 2020-10-07 15:56
Yes please! I'll take this up 👍

**Comment by kavishdahekar** [comment] 2020-10-07 21:16
Just to confirm, we'll add functionality to sort the properties file to ```org.quelea.services.utils.QueleaProperties``` and then call it in ```ExitActionHandler``` somewhere here https://github.com/quelea-projection/Quelea/blob/82b9dd32a2e76c53be15f844e55f3ccfdda007f7/Quelea/src/main/java/org/quelea/windows/main/actionhandlers/ExitActionHandler.java#L120

**Comment by berry120** [comment] 2020-10-07 21:21
@kavishdahekar Yes, I think that's the best place for it. The sorting of the properties file should be handled by a separate class, then that class called from the the exit handler.

**Comment by kavishdahekar** [comment] 2020-10-07 21:51
The `java.util.Properties` extends `Hashtable` which is unordered by design.
- We can either overwrite one of its methods in our child class `QueleaProperties` so it writes a sorted list of keys. 
  - Already tried [this](https://stackoverflow.com/a/50478238/2175224) and it works.
- We could do this in a separate class as you suggested.
  - I am assuming we will have to write our own code for writing the properties to the file.
- Minimally invasive way would be to extend `QueleaProperties` from `org.apache.commons.collections4.properties.SortedProperties` instead of `java.util.Properties`. I've already tried it and it works.
  - The only drawback to this is that the properties will be sorted every time they are written.

What do you suggest?

**Comment by berry120** [comment] 2020-10-07 21:54
If we already have `SortedProperties` available to us through existing dependencies, let's just use that - I think that's the easiest and best approach. Alternatively I'd take your first suggestion. I'd go for less code over writing a separate class as I initially suggested.

I don't think it's an issue that they'll be sorted each time they're written - the overhead is low, and that helps to make it a more consistent implementation.

**Comment by kavishdahekar** [comment] 2020-10-07 21:56
Yes, `org.apache.commons.collections4.properties.SortedProperties` seems to be already available through existing dependencies.
Lets go with that then. Will raise a PR.

**Closed** 2020-10-20 18:06 UTC
Labels: good first issue, hacktoberfest

**Comment by DeeTigIT** [comment] 2020-10-21 19:19
Thanks, Kavish and Michael, for this fix! Is greatly appreciated.
