### ISSUE TITLE
Después de un tiempo de uso no se puede editar ni añadir canciones

### ISSUE THREAD

**Issue by Cyb3rG0D7** [quelea-projection/Quelea#102] opened 2019-02-11 03:39 UTC
Instalé la última noche, ya son 3 veces que después de un tiempo de uso y añadir unas letras no deja editar ni añadir más.
También los hashes no coinciden, uso esta extesión para verificar el checksum
https://addons.mozilla.org/en-US/firefox/addon/calculate-md5-sha1-hash-che-1/

**Comment by berry120** [comment] 2019-02-11 11:03
Could you attach a debug log after editing no longer works to see if we can
narrow down the issue? Thanks!

**Comment by Cyb3rG0D7** [comment] 2019-02-17 14:45
Solo se edita una canción y a la segunda ya no se peude..
[quelea-debuglog-error editando.txt](https://github.com/quelea-projection/Quelea/files/2873039/quelea-debuglog-error.editando.txt)

**Comment by berry120** [comment] 2019-02-19 21:48
Afraid there's nothing in the debug log that indicates a problem. When you say editing doesn't work (apologies if that's a bad translation), what exactly isn't working? Are you able to take a screen recording of the issue so we can see first hand what's going on? Thanks

**Comment by ArvidNy** [comment] 2019-02-26 16:06
I can't reproduce this either I'm afraid. Maybe you could also attach your quelea.properties file as well so that we could see if there's anything in the way that you have set things up that could help us reproduce it. If the hashes differ it might be a good idea to download Quelea again and see if that helps, but by the looks of that add-on you linked to it doesn't support SHA256, so that's probably the reason why it differs.

**Comment by ArvidNy** [comment] 2019-02-27 19:00
@Cyb3rG0D7, are you using the second beta? In that case, it might be related to #103.

**Comment by Cyb3rG0D7** [comment] 2019-02-28 15:04
En la última noche hay el error de que no deja editar canciones después de agregar algunas o editar, y error del checksum
En beta 2 no hay problema de la edición. pero si está igual el error del checksum

**Comment by Cyb3rG0D7** [comment] 2019-03-01 03:11
Después de solo añadir y editar la primera canción, la opción de etidar y añadir nuevo ya no funciona
Link bug video: https://drive.google.com/open?id=1uUzXAXUgZt2xgTPX0HTaajcO_C5d781N

**Comment by ArvidNy** [comment] 2019-03-04 20:55
That's strange! I does look like there should be some kind of error in the debug log after that behavior but I suppose you've already checked that there's nothing new in the debug log after recreating that issue? Did I understand you correctly that you can edit normally in the second beta but not in the latest CI?

**Comment by Cyb3rG0D7** [comment] 2019-03-04 21:22
En la última CI está el error. en beta2 no me a pasado.
Para poder editar o añadir algo debo reiniciar el programa para que funciona la opción de editar.

**Comment by ArvidNy** [comment] 2019-03-04 22:27
Could you maybe try to run Quelea through CMD and see if you can get any more information from that output?
`java -jar Quelea.jar` (Just let me know if you need more information that this to do it!)
It's farfetched, but I think I've found somethings there that I haven't found in the debug log so it might be worth a shot.

Can you see any system in when it happens, like with a certain song or if you add certain amount of songs, only in the schedule but not in the database etc.?

**Comment by berry120** [comment] 2019-04-01 12:07
Just tidying up a few issues - I'll close this off for now as we haven't had any activity for 28 days, and it isn't something we can reproduce. If you have any new information about it then feel free to reopen.

**Closed by berry120** 2019-04-01 12:07 UTC
