### ISSUE TITLE
Options window doesn't fit on smaller screens

### ISSUE THREAD

**Issue by mbsrz1972** [quelea-projection/Quelea#129] opened 2019-05-03 09:27 UTC
Maybe it's good time (as number of items increases) to rearrange options. Options window is too high to fit my 1366x768 resolution screen so it is hard click button "ok".

**Comment by berry120** [comment] 2019-05-03 10:13
Already on the radar 👍  Duplicate of #112 .

**Closed by berry120** 2019-05-03 10:13 UTC
