### ISSUE TITLE
Error in bibles .xmm

### ISSUE THREAD

**Issue by Dazmed707** [quelea-projection/Quelea#324] opened 2021-01-03 13:03 UTC
Verse by verse is not shown as stated

![image](https://user-images.githubusercontent.com/35184132/103479219-30905600-4d9a-11eb-9586-5e1458219f48.png)

![image](https://user-images.githubusercontent.com/35184132/103479203-1e161c80-4d9a-11eb-9edd-e7b391b3ebb3.png)

**Comment by berry120** [comment] 2021-02-01 20:16
Can you check you're not falling foul of this issue? If so it should be fixed in the latest nightly. https://github.com/quelea-projection/Quelea/issues/302

**Comment by berry120** [comment] 2021-03-08 21:25
Just cleaning older issues up, so closing as a duplicate of #302. If it's not, feel free to reopen.

**Closed by berry120** 2021-03-08 21:25 UTC
