### ISSUE TITLE
text size in lyric webpage

### ISSUE THREAD

**Issue by lemelind** [quelea-projection/Quelea#344] opened 2021-03-08 00:54 UTC
Hello,
I want to thank you for all the great work you have done in this software.
Like issue : #334, the Bible text size are very small in lyric webpage, the song text size are perfect.
I use the last CI version (from today 03-07-2021)
Thanks a lot,
David

**Comment by berry120** [comment] 2021-03-08 00:57
Hey, just to check - are you saying the issue isn't fixed in the latest CI from around 5 hours ago? If so I'll need to take a deeper look.

**Comment by lemelind** [comment] 2021-03-08 00:58
the last issue was fixed greatfully
now the stage view for Bible text size are perfect
this issue is only for Bible text size in lyric webpage

**Comment by lemelind** [comment] 2021-03-08 01:04
song:
![2021-03-07 20_00_10-Quelea Lyrics Display](https://user-images.githubusercontent.com/80229539/110261978-29dfb400-7f80-11eb-9175-10ce9301cb46.png)
Bible:
![2021-03-07 20_01_21-Quelea Lyrics Display](https://user-images.githubusercontent.com/80229539/110262001-39f79380-7f80-11eb-9738-913bacc1be64.png)

**Closed** 2021-03-08 21:05 UTC

**Comment by berry120** [comment] 2021-03-08 21:23
This should now be fixed in the latest nightly 👍
