### ISSUE TITLE
2 Bugs/Issues in OS X: Quick Edit

### ISSUE THREAD

**Issue by Bogdinamite** [quelea-projection/Quelea#114] opened 2019-04-06 17:51 UTC
2 Bugs/Issues on the Newst OS X on an imac.

Quick Edit (Shift+Click) in the Live Window doesn't select the correct verse/line break to edit. The program auto selects the first line.
It would also be nice for it to automatically change the verse that is currently being displayed live when edited. Also while holding shift, i get a corrupted icon for the mouse looking like an icon sprite list.

Just bringing these issues to light because I think the quick edit feature would be really helpful if it worked. 

Also the the .jar file has no logo.

Thank you!

**Comment by berry120** [comment] 2019-04-06 20:16
Thanks, we'll take a look!

(The icon issue should be solved in the CI release however: https://github.com/quelea-projection/Quelea/issues/108)

**Comment by berry120** [comment] 2019-06-08 22:18
We would take a look, but lack of Macs on the dev team mean that we can't feasibly at the moment. If a Mac user / developer is able to pick these up, that'd be fantastic. Otherwise not a great deal we can do at present.

**Comment by huantianad** [comment] 2020-03-08 16:53
Windows 10 user, also having quick edit select the first line. Not sure if it's a mac related issue, but I also do not have a mac to test it on.

**Comment by ArvidNy** [comment] 2020-10-23 14:57
You're right, `shift + click` did not work as intended whereas `ctrl + click` did. This should now be resolved in the latest commit.

**Closed by ArvidNy** 2020-10-23 14:57 UTC
Labels: bug, help wanted
