### ISSUE TITLE
Elvanto OAuth log in workflow is not working

### ISSUE THREAD

**Issue by navhaxs** [quelea-projection/Quelea#210] opened 2019-10-19 12:24 UTC
Hey guys, first up just wanted to say that as far as open source lyric screen software goes, I have been really liking Quelea :)

Anyways - I am having trouble with the Elvanto integration. Neither myself nor my friend are able to log in.

![image](https://user-images.githubusercontent.com/5162718/67144778-58df8200-f2c6-11e9-8aa7-2881a74c62dc.png)

I tested using the latest 2019.1 release from the Quelea website.

If this is coding issue in the integration code I don't mind spending further time to investigate, this month being hacktober and all 😉

Has anyone else used the Elvanto integration feature in Quelea recently? (Who knows, bug might be on Elvanto's end...)

Or perhaps I'm doing something wrong... does the client id etc. get built into the release app and debug builds?

My friend recently wrote a little project which utilises the Elvanto OAuth workflow, and I can confirm that my actual credentials are definitely working there. And I log into the main Elvanto web app frequently to manage our rosters.

**Comment by jakobmatt** [comment] 2019-10-23 14:15
Hi,
I tried running 2019.1 and imported a service plan from Elvanto - and at least the songs can be fetched successfully. 

But it still requires adding that parameter "elevanto.client.id" in your quelea.properties file (in C:\users\USERNAME.quelea), as described in issue #86

**Comment by navhaxs** [comment] 2019-10-24 09:26
Ahh I see - thanks! My bad for not searching through the GitHub issues.

Since this is the case, I think it would be good for this to be noted somewhere in the [Quelea User Documentation](https://quelea-projection.github.io/docs/), as that was where I did attempt to look for help before opening this issue.

**Comment by berry120** [comment] 2020-04-22 21:23
This has now been added to the documentation - we'll add it to the options dialog as well in due course.

In the meantime marking this as a Duplicate of #86 so we don't have two bugs open with the same issue.

**Closed by berry120** 2020-04-22 21:23 UTC
