### ISSUE TITLE
Database does not save after adding a translation to song

### ISSUE THREAD

**Issue by GW391** [quelea-projection/Quelea#559] opened 2022-09-09 19:16 UTC
Juts tried to add a translation to an existing song, the song saves in the scedule, but the database never saves. when I close Quelea the song is removed from the database. 

I am adding Ukranian to a linked song in the schedule. 

I created a new single slide song in the database and that seemed to work, but updating a song in the dabase and the same thing happens.

when updating from the schedule the songs are remaining in the schedule, but are becoming orphaned, now with the copied logo, editing again, and the updating database bar appers and remains, not saving the song into the database. 

Version 2022.0
Can't find an error log

Edit:
Ok I think this might be a databse issue with my DB, I have deleted the existing DB, and tried editing the same schedule, the record has saved correctly, and quickly.

I will keep testing, and looking for a cuase, and update if I find anything else. 

Edit 2:
No cuase found, but put existing DB back in place, Exported to Quelea Song Pack, 
Closed Quelea, deleted datbase and re-opened Quelea
importd song pack into empty database 
edited the translated song in the schedule 
new song created in new DB, and saved with Translation

DB now 1/2 the size, hopfully this reduction in size is removing the problem and not lost anything in the process, 

Anywya must be a datbase issue. which is now fixed.

**Comment by berry120** [comment] 2023-12-31 18:58
Closing this one off as I can't reproduce it and looks like it's a transient issue from the description, but if you do manage to reproduce it reliably and want us to look into it further, please feel free to reopen.

**Closed by berry120** 2023-12-31 18:58 UTC
