### ISSUE TITLE
Please release Quelea to AUR

### ISSUE THREAD

**Issue by kanglinyao** [quelea-projection/Quelea#258] opened 2020-06-19 05:03 UTC
I absolutely love Quelea, but installing Quelea in Arch-based Linux is never an easy task. 
Unfortunately, I hate snapd as much as I love Quelea. Please stopp using snapd.
Please publish final Quelea to Arch community,
and beta release to AUR.

**Comment by berry120** [comment] 2020-06-22 08:50
We have hundreds of people actively using the snap package, so afraid that's not going anywhere any time soon.

No plans as of yet to publish to AUR, but ideally it's something we'd look at in a future release. Unlikely that the core devs will get around to it, but happy to receive any contributions to do so via PR.

**Comment by berry120** [comment] 2020-06-22 08:59
Notice this is a duplicate of #223 - so we'll track this progress there instead.

**Closed by berry120** 2020-06-22 08:59 UTC
Labels: accepted, enhancement
